import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BsFillMoonStarsFill, BsCodeSlash } from 'react-icons/bs'
import { MdOutlineSecurity } from 'react-icons/md'
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { CgWebsite }from 'react-icons/cg';
import { Icon } from '@iconify/react';
import Image from "next/image";
import boomerang from "../public/boomerang.png";
import shoppy from "../public/shoppy.png";
import skate from "../public/skate.png";
import garage from "../public/garage.png";
import mauricio from "../public/mauricio.jpeg"

import { useState } from "react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mauricio Murta Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-400 lg:text-2xl text-'> Mauricio Murta</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500
               to-teal-500 bg-cyan-500 text-white px-4 py-2 
               rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl '>Mauricio Murta</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-300'>Computer Science Student</h3>
            <p className='text-base py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400'>
              Based in Dublin <br /> 
              Interested in full stack development and cyber security.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-12 py-3 text-gray-600'>
            <a href="https://github.com/MMPodesta" className='hover:text-gray-900 dark:hover:text-gray-400' target='_blank'><AiFillGithub/></a>
            <a href="https://www.linkedin.com/in/mauriciomurta/" className='hover:text-gray-900 dark:hover:text-gray-400' target='_blank'><AiFillLinkedin/></a>
            <a href="https://tryhackme.com/p/gangsta6" className='hover:text-gray-900 dark:hover:text-gray-400' target='_blank'><Icon icon="simple-icons:tryhackme" /></a>
            <a href="https://leetcode.com/MMPodesta/" className='hover:text-gray-900 dark:hover:text-gray-400' target='_blank'><Icon icon="simple-icons:leetcode" /></a>
          </div>
        </section>
        
        <section>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={mauricio} layout='fill' objectFit='cover'/>
          </div>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-300'>My Skills</h3>
            <p className='text-md py-2 leading-8 text-gray-80 dark:text-gray-400 lg:text-lg'>
              Expected to graduate in 2024. Throughout my degree, I have learned a lot about the design, development and maintenance of software.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400 lg:text-lg'>
              My core skills are related to web development, objected-oriented programming and cyber security.
            </p>
          </div>
          <div className='lg:flex lg:justify-around gap-10'>
            <div className='text-center shadow-lg shadow-teal-700 p-10 rounded-xl my-10'>
              <CgWebsite  className='text-8xl mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>
                Web Development
              </h3>
              <p className='py-2 dark:text-gray-400'>
                Creating elegant designs suited for your project
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
            </div>
            <div className='text-center shadow-lg shadow-teal-700 p-10 rounded-xl my-10'>
              <BsCodeSlash  className='text-8xl mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>
                Programming
              </h3>
              <p className='py-2 dark:text-gray-400'>
                Creating elegant designs suited for your project
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
            </div>
            <div className='text-center shadow-lg shadow-teal-700 p-10 rounded-xl my-10'>
              <MdOutlineSecurity  className='text-8xl mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>
                Cyber Security
              </h3>
              <p className='py-2 dark:text-gray-400'>
                Creating elegant designs suited for your project
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-gray-400'>Photoshop</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-300'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-80 dark:text-gray-400 lg:text-lg'>
              I am a computer science student based in Dublin, 
              Interested in full stack development and cyber security.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400 lg:text-lg'>
              I am a computer science student based in Dublin, 
              Interested in full stack development and cyber security.
              I am a computer science student based in 
              <span className='text-teal-500'> Dublin</span>, 
              Interested in full stack development and cyber security.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <a href="https://knuth.griffith.ie/~s3065078/ass03/" target='_blank'><Image src={boomerang} className='rounded-lg object-cover' width={'100%'} height={'100%'} /></a>
            </div>
            <div className='basis-1/3 flex-1'>
              <a href="https://store.mauriciomurta.com" target='_blank'><Image src={shoppy} className='rounded-lg object-cover' width={'100%'} height={'100%'}/></a>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={skate} className='rounded-lg object-cover' width={'100%'} height={'100%'}/>
            </div>
            <div className='basis-1/3 flex-1'>
              <a href="https://knuth.griffith.ie/~s3065078/ass02/home.html" target='_blank'><Image src={garage} className='rounded-lg object-cover' width={'100%'} height={'100%'}/></a>
            </div>
          </div>
        </section>
      </main>
    </div>
    </>
  );
}
