import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BsFillMoonStarsFill, BsCodeSlash } from 'react-icons/bs'
import { MdOutlineSecurity } from 'react-icons/md'
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { CgWebsite }from 'react-icons/cg';
import { Icon } from '@iconify/react';
import Image from "next/image";
import boomerang from "../public/boomerang.png";
import shoppy from "../public/shoppy.png";
import skate from "../public/skate.png";
import garage from "../public/garage.png";
import mauricio from "../public/mauricio.jpeg"
import {ListItem} from "../components/list-item";
import { useState } from "react";
import Link from 'next/link';
import { LinkItem } from '@/components/link-item';
import { PortfolioItem } from '@/components/portfolio-item';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mauricio Murta Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-400 lg:text-2xl text-'> Mauricio Murta</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl 
                hover:text-yellow-400 lg:text-3xl dark:text-yellow-400 dark:hover:text-yellow-300 '/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500
               to-teal-500 bg-cyan-500 text-white px-4 py-2 
               rounded-md ml-8' href='MauricioMurta_CV.pdf' target='_blank'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl '>Mauricio Murta</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-300'>Computer Science Student</h3>
            <p className='text-base py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-400'>
              Based in Dublin <br /> 
              Interested in full stack development and cyber security.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-12 py-3 text-gray-600 lg:text-7xl'>
            <LinkItem list={[
              {id: 1 , link: 'https://github.com/MMPodesta', icon: <AiFillGithub/>},
              {id: 2 , link: 'https://www.linkedin.com/in/mauriciomurta/', icon: <AiFillLinkedin/>},
              {id: 3 , link: 'https://tryhackme.com/p/MMPodesta', icon: <Icon icon="simple-icons:tryhackme"/>},
              {id: 4 , link: 'https://leetcode.com/MMPodesta/', icon: <Icon icon="simple-icons:leetcode"/>}
            ]}/>
          </div>
        </section>
        
        <section>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={mauricio} alt='' fill style={{objectFit:"cover"}}/>
          </div>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-300'>My Skills</h3>
            <p className='text-md py-2 leading-8 text-gray-80 dark:text-gray-400 lg:text-lg'>
              Expected to graduate in 2024. Throughout my degree, I have learned a lot about the design, development and maintenance of software.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400 lg:text-lg'>
              My core skills are related to web development, objected-oriented programming and cyber security.
            </p>
          </div>
          <div className='lg:flex  gap-10'>
            <div className='text-center shadow-lg shadow-teal-700 p-10 rounded-xl my-10 hover:shadow-teal-400'>
              <CgWebsite  className='text-8xl mx-auto dark:text-teal-700'/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>
                Web Development
              </h3>
              <p className='py-2 dark:text-gray-400 '>
                Development of responsive database-backed websites. <br /> Making use of modern frameworks and libraries.
              </p>
              <h4 className='py-4 text-teal-600 text-lg'>Web tools I use</h4>
              <ListItem children={['Next.js - React', 'Tailwind CSS', 'Firebase - MySql']}/>
            </div>
            <div className='text-center shadow-lg shadow-teal-700 p-10 rounded-xl my-10 hover:shadow-teal-400'>
              <BsCodeSlash  className='text-8xl mx-auto dark:text-teal-700'/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>
                Programming
              </h3>
              <p className='py-2 dark:text-gray-400'>
                Backend deveolpment aware of testing,<br /> concurency, time complexity, OOP and optimization.
              </p>
              <h4 className='py-4 text-teal-600 text-lg'>Programming tools I use</h4>
              <ListItem children={['Java - Gradle', 'JUnit5', 'Python']}/>

            </div>
            <div className='text-center shadow-lg shadow-teal-700 p-10 rounded-xl my-10 hover:shadow-teal-400'>
              <MdOutlineSecurity  className='text-8xl mx-auto dark:text-teal-700'/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-gray-300'>
                Cyber Security
              </h3>
              <p className='py-2 dark:text-gray-400'>
                In the top 2% of learning platform tryhackme.com <br /> Knowledge on pentesting, privesc and industry standards.
              </p>
              <h4 className='py-4 text-teal-600 text-lg'>Security tools I use</h4>
              <ListItem children={['Kali Linux', 'Burp Suite', 'Metasploit']}/>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-gray-300'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-80 dark:text-gray-400 lg:text-lg'>
              My portfolio contains personal and university projects realated to web development.
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-400 lg:text-lg'>
             They are all optimized to work either on small or large screens.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <PortfolioItem list={[
              {id: 1 , link: 'https://knuth.griffith.ie/~s3065078/ass03/', photo: boomerang},
              {id: 2 , link: 'https://store.mauriciomurta.com', photo: shoppy},
              {id: 3 , link: 'https://skate.mauriciomurta.com/home.html', photo: skate},
              {id: 4 , link: 'https://knuth.griffith.ie/~s3065078/ass02/home.html', photo: garage}
            ]}/>
          </div>
        </section>
      </main>
    </div>
    </>
  );
}
